[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
actix-service = "1.0.0"
futures = "0.3"
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
json = "0.12"
git2 = "0.13"
regex = "*"
lazy_static = "1.4.0"
