version: "3"

networks:
  web:
    external: true

services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ci
    image: ci
    ports:
      - "8081:8081"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:~/.ssh
    networks:
      - web
