version: "3"

networks:
  web:
    external: true

services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_KEY_PASSWORD: "${SSH_KEY_PASSWORD}"
        SSH_KEY_PATH: "${SSH_KEY_PATH}"
        ENV_PROFILE: "${ENV_PROFILE}"
    hostname: ci
    image: ci
    ports:
      - "8081:8081"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/appuser/.ssh
    networks:
      - web
