version: "3"

networks:
  web:
    external: true

services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_KEY_PASSWORD: "${SSH_KEY_PASSWORD}"
        SSH_KEY_PATH: "${SSH_KEY_PATH}"
        ENV_PROFILE: "${ENV_PROFILE}"
        DOCKER_GROUP_ID: "${DOCKER_GROUP_ID}"
    hostname: ci
    image: ci
    ports:
      - "8083:8083"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SSH_KEY_PATH}:/home/appuser/.ssh/ci
    networks:
      - web
